README.md

Merge this to receive a badge indicating the number of issues in the ready column on your waffle.io board at https://waffle.io/healthbam/healthbam
This was requested by a real person (user mckoon) on waffle.io, we're not trying to spam you.

Issue #3: waffle.io Badge

---

.gitignore
README.md
client/src/main/webjar/app.js
config/application.properties

Updates README.md with IntelliJ set up instructions.
Adds .idea/ to .gitignore.
Changes log statement in app.js as a test.
Changes DB account from "ryan" to "healthbam_sql".
Closes #37.

Issue #37: Add IntelliJ .idea to .gitignore

---

.travis.yml

* Adds yml file for configuring continuous integration.

closes #39: Add Travis CI yml file to project

---

.travis.yml

* Adds before_cache and cache explained in travis-ci's docs.
https://docs.travis-ci.com/user/languages/java/#Caching

Fix Travis CI gradle cache

---

src/main/java/org/hmhb/ViewsController.java
src/main/resources/static/index.html

* Adds ViewsController to handle forwarding to the index.html.
* Handles "", "/", "/views", "/views/", "/views?x=y", and "/views/abc".

closes #44: Add "views" route to serve index.html

---

src/main/java/org/hmhb/audit/DefaultAuditHelper.java
src/test/java/org/hmhb/audit/DefaultAuditHelperTest.java

* Adds HttpServletRequest to DefaultAuditHelper for obtaining real IP address.
* Updates unit tests.

closes #48: Add real IP to audit info

---

src/main/resources/schema.sql

* Removes unnecessary drop tables for hmhb_user now that it is gone.

Remove unnecessary drop tables for hmhb_user

---

client/src/main/webjar/app.scss

* Changes ui-view positioning to relative.

Issue #55: Map Positioning

---

client/src/main/webjar/main/main.component.js

closes Issue 69

---

src/main/java/org/hmhb/program/Program.java
src/main/resources/data.sql
src/main/resources/schema.sql
src/test/java/org/hmhb/program/DefaultProgramServiceTest.java

* Adds city property, accessor, and modifier to Program.
* Adds city column to program table.
* Adds city to dummy data.
* Uses real addresses for dummy data.
* Updates tests.

Issue #90: Add City to Program

---

client/src/main/webjar/map/map.component.js
client/src/main/webjar/map/map.html
client/src/main/webjar/map/map.module.js
client/src/test/webjar/map/map.component.spec.js

* Shows all programs on map.
* Uses purple material design place icon.
* Reduces noise on the map so the icons stand out.
Closes #94.

Issue #94: Programs on Map

---

client/src/main/webjar/program-form-dialog/program-form-dialog.controller.js
client/src/main/webjar/program-form-dialog/program-form-dialog.html
client/src/test/webjar/program-form-dialog/program-form-dialog.controller.spec.js

* Allows users to select or create new organization.
* Adds save REST call for Program.
* Shows toast if Program save fails.
* Program $resource properties match server names.
NOTES:
There are still some fields on Program not modeled on the backend yet.
Organization fetch errors not handled yet.
Domain object changes based on recent feedback will change this.
Specifically, the new one-to-many relationship of Program to locations.

Issue #92: Program Form HTTP Integration

---

CONTRIBUTING.md
README.md

* Creates CONTRIBUTING.md to explain the rules and workflow for code changes.
* Adds a "Creating Issues" section with a link and instructions.
* Adds a "Committing Code" section that explains the Issue requirement and commit messages rules.
* Adds a "Submitting Pull Requests" section to explain the git workflow, forks, and pull-requests.
* Adds a Contributing section to README.md that links to the new CONTRIBUTING.md.

Issue #99: Collaboration Rules Needed

---

client/src/main/webjar/counties-field/counties-field.component.js
client/src/main/webjar/counties-field/counties-field.html
client/src/main/webjar/counties-field/counties-field.module.js
client/src/main/webjar/county/county.module.js
client/src/main/webjar/county/county.resource.js
client/src/main/webjar/program-form-dialog/program-form-dialog.html
client/src/main/webjar/program-form-dialog/program-form-dialog.module.js
client/src/main/webjar/program-form-dialog/program-form-dialog.scss
client/src/main/webjar/program-form-dialog/program-form-dialog.service.js
client/src/test/webjar/counties-field/counties-field.component.spec.js
client/src/test/webjar/county/county.resource.spec.js
client/src/test/webjar/program-form-dialog/program-form-dialog.service.spec.js

* Adds counties-field component for chips.
* Adds counties-field to program-form-dialog.
* Adds County $resource.

Issue #105: Program County Chips

---

src/main/java/org/hmhb/exception/programarea/ProgramAreaNotFoundException.java
src/main/java/org/hmhb/programarea/DefaultProgramAreaService.java
src/main/java/org/hmhb/programarea/ProgramArea.java
src/main/java/org/hmhb/programarea/ProgramAreaController.java
src/main/java/org/hmhb/programarea/ProgramAreaDao.java
src/main/java/org/hmhb/programarea/ProgramAreaService.java
src/main/resources/data.sql
src/main/resources/schema.sql
src/test/java/org/hmhb/programarea/DefaultProgramAreaServiceTest.java
src/test/java/org/hmhb/programarea/ProgramAreaControllerTest.java

* Adds ProgramArea object, controller, service & dao.
* Creates ProgramArea table.
* Inserts all ProgramArea records into table.

Issue-107: Program Area Support

---

client/src/main/webjar/program-area/program-area.module.js
client/src/main/webjar/program-area/program-area.resource.js
client/src/main/webjar/program-form-dialog/program-form-dialog.module.js
client/src/test/webjar/program-area/program-area.resource.spec.js
src/main/resources/schema.sql

* Adds ProgramArea $resource.
* Fixes bug dropping program_area table if already created.

Issue #109: ProgramArea Resource

---

client/src/main/webjar/program-form-dialog/program-form-dialog.controller.js
client/src/test/webjar/program-form-dialog/program-form-dialog.controller.spec.js

* Updates Program Form to use ProgramArea resource.
* Adds toast error handling on Organization fetch failure.
* Adds toast error handling on ProgramArea fetch failure.

Issue #111: Use Program Area Resource

---

client/src/main/webjar/program-form-dialog/program-form-dialog.controller.js
client/src/main/webjar/program-form-dialog/program-form-dialog.html
client/src/test/webjar/program-form-dialog/program-form-dialog.controller.spec.js

* Shows loading spinner during load of dialog.
* Shows loading spinner during save of program.

Issue #114: Program Dialog Spinner

---

src/main/java/org/hmhb/program/Program.java
src/main/resources/data.sql
src/main/resources/schema.sql

* Creates program_county join table.
* Adds counties to Program object and table.
* Adds sample program_county data.

closes #116: Add Counties To Program

---

client/src/main/webjar/map-query/map-query.module.js
client/src/main/webjar/map-query/map-query.resource.js
client/src/main/webjar/map/map.module.js
client/src/test/webjar/map-query/map-query.resource.spec.js
src/main/java/org/hmhb/mapquery/DefaultMapQueryService.java
src/main/java/org/hmhb/mapquery/MapQuery.java
src/main/java/org/hmhb/mapquery/MapQueryController.java
src/main/java/org/hmhb/mapquery/MapQueryResult.java
src/main/java/org/hmhb/mapquery/MapQuerySearch.java
src/main/java/org/hmhb/mapquery/MapQueryService.java
src/test/java/org/hmhb/mapquery/DefaultMapQueryServiceTest.java
src/test/java/org/hmhb/mapquery/MapQueryControllerTest.java

* Creates MapQuery $resource.
* Creates skeleton MapQuery REST endpoint for testing.

Issue 120 map query resource

---

client/src/main/webjar/toolbar/toolbar.html

* Adds a "Need a Doctor?" link to toolbar for public users.

Issue #126: Need a Doctor Link

---

src/main/java/org/hmhb/county/CountyDao.java
src/main/java/org/hmhb/county/DefaultCountyService.java
src/main/java/org/hmhb/programarea/DefaultProgramAreaService.java
src/main/java/org/hmhb/programarea/ProgramAreaDao.java
src/test/java/org/hmhb/county/DefaultCountyServiceTest.java
src/test/java/org/hmhb/programarea/DefaultProgramAreaServiceTest.java

* Orders County results by ascending name.
* Orders ProgramArea results by ascending name.
* Updates unit tests.

closes #155: Fix order of counties & program areas

---

client/src/main/webjar/program-form-dialog/program-form-dialog.html

* Updates "Primary goal #" to "Primary program goal #".
* Updates "Measurable outcome #" to "Measurable program outcome #".

closes #153: Update labels per customer feedback

---

client/src/main/webjar/main/main.component.js

* Adds logs message to main screen.

closes #70: Add log message

---

client/src/main/webjar/app.js
client/src/main/webjar/program-details/program-details.component.js
client/src/main/webjar/program-details/program-details.html
client/src/main/webjar/program-details/program-details.module.js
client/src/main/webjar/program-details/program-details.route.js
client/src/main/webjar/program-form-dialog/program-form-dialog.controller.js
client/src/test/webjar/program-details/program-details.component.spec.js
src/main/java/org/hmhb/ViewsController.java

* Creates module, route and skeleton component for program-details.
* Fixes bug in Views Controller server-side not handling slashes.
Closes #182

Issue #182: Program Details Route

---

src/main/java/org/hmhb/mapquery/DefaultMapQueryService.java
src/main/java/org/hmhb/mapquery/MapQuerySearch.java

* Adds Program to MapQuery.
* Limits Programs returned to Program input.
Closes #190.

Issue #190: MapQuery Program Filtering

---

client/src/main/webjar/main/main.component.js

* Removes training console logging.

closes #192: Clean up browser console logging

---

src/main/java/org/hmhb/program/Program.java
src/main/resources/data.sql
src/main/resources/schema.sql

* Creates program_program_area join table.
* Adds List<ProgramArea> to Program object.
* Adds sample program_program_area data.

closes #140: Add ProgramAreas to Program

---

src/main/java/org/hmhb/program/Program.java
src/test/java/org/hmhb/program/DefaultProgramServiceTest.java

* Changes countiesServed and programAreas to a Set.
* Updates unit tests.

closes #197: Fix duplicate county & program areas

---

client/src/main/webjar/program-form-dialog/program-form-dialog.html
src/main/java/org/hmhb/exception/program/ProgramStartYearRequiredException.java
src/main/java/org/hmhb/program/DefaultProgramService.java
src/main/java/org/hmhb/program/Program.java
src/main/resources/schema.sql
src/test/java/org/hmhb/program/DefaultProgramServiceTest.java

* Removes required from startYear on program form.
* Removes NonNull constraint in DB and JPA object for startYear.
* Removes ProgramStartYearRequiredException.
* Updates unit tests.

closes #185: Make StartYear Optional on Program

---

client/src/main/webjar/counties-field/counties-field.component.js
client/src/main/webjar/counties-field/counties-field.html
client/src/main/webjar/map-config/map-config.constant.js
client/src/main/webjar/map-config/map-config.module.js
client/src/main/webjar/map/map.component.js
client/src/main/webjar/map/map.html
client/src/main/webjar/map/map.module.js
client/src/main/webjar/map/map.scss
client/src/main/webjar/program-details/program-details.component.js
client/src/main/webjar/program-details/program-details.html
client/src/main/webjar/program-details/program-details.module.js
client/src/main/webjar/program-details/program-details.scss
client/src/main/webjar/program-form-dialog/program-form-dialog.html
client/src/test/webjar/map-config/map-config.constant.spec.js
client/src/test/webjar/map/map.component.spec.js
client/src/test/webjar/program-details/program-details.component.spec.js

* Closes #128.
* Implements page with multiple cards.
* Adds toolbar with Program name and actions.
* Adds readonly mode to counties-field.
* Adds toggling county list.
* Adds loading spinner.
* Creates map-config constant for shared styles.

Issue #128: Program Details

---

integration-tests/input-customer-data.jmx

* Creates an integration test file with the customer supplied data.
* Includes HMHB Prenatal Education Program data.
* Includes HMHB Breastfeeding Friendly Establishments data.
* Includes DPH's Baby Luv Program data.

closes #187: Add customer data to integration test

---

src/main/java/org/hmhb/kml/DefaultKmlPlacemarkService.java
src/test/java/org/hmhb/kml/DefaultKmlPlacemarkServiceTest.java

* Adds organization and details link to program balloon.

Issue #158: Simple Program Info

---

client/src/main/webjar/create-program/create-program.component.js
client/src/main/webjar/program-details/program-details.component.js
client/src/main/webjar/program-details/program-details.html
client/src/main/webjar/program-details/program-details.module.js
client/src/main/webjar/program-form-dialog/program-form-dialog.controller.js
client/src/main/webjar/program-form-dialog/program-form-dialog.html
client/src/main/webjar/program-form-dialog/program-form-dialog.service.js
client/src/test/webjar/create-program/create-program.component.spec.js
client/src/test/webjar/program-details/program-details.component.spec.js
client/src/test/webjar/program-form-dialog/program-form-dialog.controller.spec.js
client/src/test/webjar/program-form-dialog/program-form-dialog.service.spec.js

* Adds create and edit functions to programFormDialogService.
* Adds trackBy to organizations ng-repeat to fix object equality.
* Opens program-form-dialog from Edit button on program-details.
Closes #129

Issue-129: Edit Program

---

src/main/java/org/hmhb/kml/DefaultKmlService.java
src/main/java/org/hmhb/kml/KmlController.java
src/main/java/org/hmhb/kml/KmlService.java
src/main/java/org/hmhb/mapquery/DefaultMapQueryService.java
src/test/java/org/hmhb/kml/DefaultKmlServiceTest.java
src/test/java/org/hmhb/kml/KmlControllerTest.java
src/test/java/org/hmhb/mapquery/DefaultMapQueryServiceTest.java

* Adds countyId to the kml url.
* Changes shading to only shade the passed in county if specified.

closes #215: Fix county search

---

client/src/main/webjar/program-details/program-details.component.js
client/src/main/webjar/program-details/program-details.html
client/src/test/webjar/program-details/program-details.component.spec.js

* Adds delete program functionality.

Issue #142: Delete Program

---

integration-tests/input-customer-data.jmx
src/main/java/org/hmhb/program/Program.java
src/main/resources/schema.sql

* Adds otherProgramAreaExplanation to Program object.
* Adds other_program_area_explanation to program table.
* Updates integration test data.

closes #184: Add otherProgAreaExplanation to program

---

client/src/main/webjar/program-details/program-details.html
client/src/main/webjar/program-form-dialog/program-form-dialog.html

* Adds client-side support for programs serving all counties.
Closes #208

Issue #208: Serves All Counties

---

Procfile.windows
client/src/main/webjar/app.js
client/src/main/webjar/organization-list/organization-list.component.js
client/src/main/webjar/organization-list/organization-list.html
client/src/main/webjar/organization-list/organization-list.module.js
client/src/main/webjar/organization-list/organization-list.route.js
client/src/test/webjar/organization-list/organization-list.component.spec.js
runInWindows.bat

This PR includes two commits - one for setting up the organizations edit/delete page (but that's not finished yet, so it doesn't close the issue), and one committing the .bat and Procfile.windows files I need to build the project on Windows.
ETA: Still trying to figure out how the testing works, but here's a functional Organization List page.
ETA: completed, commits squashed

Issue143 list organizations

---

client/src/main/webjar/app.js
client/src/main/webjar/organization-details/organization-details.component.js
client/src/main/webjar/organization-details/organization-details.html
client/src/main/webjar/organization-details/organization-details.module.js
client/src/main/webjar/organization-details/organization-details.route.js
client/src/test/webjar/organization-details/organization-details.component.spec.js

(originally committed as issue 144)

#219 - org details view and test file, but no edit dialog yet

---

src/main/java/org/hmhb/kml/jaxb/KmlLineStyle.java

* Adds javadoc for KmlLineStyle.

closes #236: Update javadocs

---

client/src/main/webjar/authentication/authentication.component.js
client/src/main/webjar/authentication/authentication.html
client/src/main/webjar/authentication/authentication.module.js
client/src/main/webjar/authentication/authentication.scss
client/src/main/webjar/authentication/authentication.service.js
client/src/main/webjar/create-program/create-program.component.js
client/src/main/webjar/create-program/create-program.html
client/src/main/webjar/create-program/create-program.module.js
client/src/main/webjar/organization-details/organization-details.component.js
client/src/main/webjar/organization-details/organization-details.html
client/src/main/webjar/organization-details/organization-details.module.js
client/src/main/webjar/program-details/program-details.component.js
client/src/main/webjar/program-details/program-details.html
client/src/main/webjar/program-details/program-details.module.js
client/src/main/webjar/sidenav/sidenav.html
client/src/main/webjar/toolbar/toolbar.html
client/src/main/webjar/toolbar/toolbar.module.js
client/src/test/webjar/authentication/authentication.component.spec.js
client/src/test/webjar/authentication/authentication.service.spec.js
client/src/test/webjar/create-program/create-program.component.spec.js
client/src/test/webjar/organization-details/organization-details.component.spec.js
client/src/test/webjar/program-details/program-details.component.spec.js

* Removes original sign in/out from sidenav.
* Adds "Sign in" toolbar button.
* Adds account menu with "Sign out" option.
* Hides create program FAB if not admin.
* Hides organization edit and delete buttons if not admin.
* Hides program edit and delete buttons if not admin.
* Adds tests for authenticationService.
* Replaces getEmail with getUser in authenticationService.
* Adds user profile picture button to toolbar.
* Adds auth component tests.
Closes #231

Issue #231: Authentication UI

---

.gitignore
client/src/main/webjar/organization-details/organization-details.component.js
client/src/main/webjar/organization-details/organization-details.module.js
client/src/main/webjar/organization-form-dialog/organization-form-dialog.controller.js
client/src/main/webjar/organization-form-dialog/organization-form-dialog.html
client/src/main/webjar/organization-form-dialog/organization-form-dialog.module.js
client/src/main/webjar/organization-form-dialog/organization-form-dialog.service.js
client/src/main/webjar/organization-list/organization-list.html
client/src/test/webjar/organization-form-dialog/organization-form-dialog.controller.spec.js
client/src/test/webjar/organization-form-dialog/organization-form-dialog.service.spec.js
runInWindows.bat

Also creates a working link from Organization List to Organization Details

Organization Form Dialog

---

client/src/main/webjar/app.js
client/src/main/webjar/navigation-list/navigation-list.component.js
client/src/main/webjar/navigation-list/navigation-list.html
client/src/main/webjar/organization-details/organization-details.component.js
client/src/main/webjar/organization-list/organization-list.component.js
client/src/main/webjar/program-details/program-details.html
client/src/main/webjar/program-list/program-list.component.js
client/src/main/webjar/program-list/program-list.html
client/src/main/webjar/program-list/program-list.module.js
client/src/main/webjar/program-list/program-list.route.js
client/src/test/webjar/navigation-list/navigation-list.component.spec.js
client/src/test/webjar/program-list/program-list.component.spec.js

* Adds program-list component and route.
* Adds program-list route to navigation-list.
* Modifies back arrow on program-details to go to program-list.
Closes #254

Issue #254: Programs List

---

client/src/main/webjar/organization-details/organization-details.html

* Disables Org delete if has programs.

Issue #225: Disable Org Delete When Has Programs

---

client/src/main/webjar/organization-form/organization-form.html
client/src/main/webjar/program-form-dialog/program-form-dialog.controller.js
client/src/main/webjar/program-form-dialog/program-form-dialog.html
client/src/main/webjar/program-form-dialog/program-form-dialog.module.js
config/application.properties
src/main/java/org/hmhb/config/DefaultConfigService.java
src/main/java/org/hmhb/config/PublicConfig.java
src/main/java/org/hmhb/exception/program/ProgramCityNameIsTooLongException.java
src/main/java/org/hmhb/exception/program/ProgramCityRequiredException.java
src/main/java/org/hmhb/exception/program/ProgramGoalIsTooLongException.java
src/main/java/org/hmhb/exception/program/ProgramOutcomeIsTooLongException.java
src/main/java/org/hmhb/exception/program/ProgramStartYearIsTooOldException.java
src/main/java/org/hmhb/exception/program/ProgramStreetAddressIsTooLongException.java
src/main/java/org/hmhb/program/DefaultProgramService.java
src/test/java/org/hmhb/authentication/DefaultAuthenticationServiceTest.java
src/test/java/org/hmhb/authentication/DefaultJwtAuthenticationServiceTest.java
src/test/java/org/hmhb/config/ConfigControllerTest.java
src/test/java/org/hmhb/config/DefaultConfigServiceTest.java
src/test/java/org/hmhb/program/DefaultProgramServiceTest.java
src/test/java/org/hmhb/url/DefaultUrlServiceTest.java

* Adds descriptive error messages to UI for organization validation errors.
* Adds descriptive error messages to UI for program validation errors.
* Adds max length validation to UI for program street address.
* Adds pattern validation to UI for program zip code.
* Adds missing server validation to city/startyear/goal/etc.
* Adds config for common validation settings between server and client.
* Fixes indention in program-form-dialog.html.
* Adds comments and organization to application.properties.

closes #252: Add err messages on client validation

---

client/src/main/webjar/organization-form/organization-form.html
client/src/main/webjar/program-form-dialog/program-form-dialog.html

* Moves org header out of org-form and above in program form.
* Fixes bug where org select defaults to new org option.
Closes #262
Closes #263

Issue #262: Organization Form Header

---

build.gradle
config/application.properties
src/main/java/org/hmhb/county/County.java
src/main/java/org/hmhb/organization/Organization.java
src/main/java/org/hmhb/program/Program.java
src/main/java/org/hmhb/programarea/ProgramArea.java
src/main/java/org/hmhb/user/HmhbUser.java

* Adds hibernate ehcache cache.
* Configures 2nd level and query caches on.
* Adds @Cacheable to our entities.

closes #266: Turn on hibernate caching

---

client/src/main/webjar/program-details/program-details.component.js
client/src/main/webjar/program-details/program-details.html
client/src/test/webjar/program-details/program-details.component.spec.js

* Hides program-details counties section when no counties covered.
Closes #264

Issue #264: Hide Counties When Empty

---

client/src/main/webjar/program-form-dialog/program-form-dialog.controller.js
client/src/test/webjar/program-form-dialog/program-form-dialog.controller.spec.js

* Sets an existing program org to the same object as in the select.
Closes #269

Issue #269: Program Org Bug

---

src/main/java/org/hmhb/authentication/DefaultJwtAuthenticationService.java
src/main/java/org/hmhb/authentication/JwtAuthenticationService.java
src/main/java/org/hmhb/csv/CsvService.java
src/main/java/org/hmhb/csv/DefaultCsvService.java
src/main/java/org/hmhb/geocode/DefaultGoogleGeocodeClient.java
src/main/java/org/hmhb/program/DefaultProgramService.java
src/main/java/org/hmhb/program/ProgramController.java
src/main/java/org/hmhb/program/ProgramService.java
src/main/java/org/hmhb/user/DefaultUserService.java
src/main/java/org/hmhb/user/UserController.java
src/main/java/org/hmhb/user/UserService.java
src/test/java/org/hmhb/csv/DefaultCsvServiceTest.java
src/test/java/org/hmhb/program/DefaultProgramServiceTest.java
src/test/java/org/hmhb/program/ProgramControllerTest.java
src/test/java/org/hmhb/user/DefaultUserServiceTest.java
src/test/java/org/hmhb/user/UserControllerTest.java

* Adds missing logging and @Timed in DefaultJwtAuthenticationService.
* Refactors JwtAuthService to offer a method to validate a token for User CSV.
* Adds CSV export for programs by flattening counties and program areas.
* Adds CSV export for users.
* Updates the unit tests.

closes #246: AddCsvExport

---

client/src/main/webjar/organization-form/organization-form.html
config/application.properties
src/main/java/org/hmhb/config/DefaultConfigService.java
src/main/java/org/hmhb/config/PrivateConfig.java
src/main/java/org/hmhb/config/PublicConfig.java
src/main/java/org/hmhb/exception/organization/OrganizationEmailIsTooLongException.java
src/main/java/org/hmhb/exception/organization/OrganizationPhoneIsTooLongException.java
src/main/java/org/hmhb/exception/organization/OrganizationUrlIsInvalidException.java
src/main/java/org/hmhb/exception/program/ProgramStateIsInvalidException.java
src/main/java/org/hmhb/exception/program/ProgramZipCodeIsInvalidException.java
src/main/java/org/hmhb/organization/DefaultOrganizationService.java
src/main/java/org/hmhb/program/DefaultProgramService.java
src/test/java/org/hmhb/authentication/DefaultAuthenticationServiceTest.java
src/test/java/org/hmhb/authentication/DefaultJwtAuthenticationServiceTest.java
src/test/java/org/hmhb/config/ConfigControllerTest.java
src/test/java/org/hmhb/config/DefaultConfigServiceTest.java
src/test/java/org/hmhb/organization/DefaultOrganizationServiceTest.java
src/test/java/org/hmhb/program/DefaultProgramServiceTest.java
src/test/java/org/hmhb/url/DefaultUrlServiceTest.java

* Refactors public/private config to encapsulate details better.
* Adds config, client, and server validation for phone too long.
* Adds config, client, and server validation for email too long.
* Adds config, client, and server validation for url too long.
* Adds server validation for valid urls.
* Adds server validation for valid states.
* Adds server validation for valid zipcodes.
* Updates the unit tests.

closes #260: Finish validation

---

integration-tests/demo-data-to-create.js

* Adds javascript used to automate creating prepared data for the demo.

closes #291: Add demo data script to source

---

client/src/main/webjar/app.js
client/src/main/webjar/navigation-list/navigation-list.component.js
client/src/main/webjar/navigation-list/navigation-list.html
client/src/main/webjar/user-list/user-list.component.js
client/src/main/webjar/user-list/user-list.html
client/src/main/webjar/user-list/user-list.module.js
client/src/main/webjar/user-list/user-list.route.js
client/src/main/webjar/user-management/user-management.module.js
client/src/main/webjar/user-management/user-management.service.js
client/src/test/webjar/navigation-list/navigation-list.component.spec.js
client/src/test/webjar/user-list/user-list.component.spec.js
client/src/test/webjar/user-management/user-management.service.spec.js

* Adds userList state with actions.
* Adds userManagement service for user actions.
* Adds item to side-nav to get to userList.
Closes #176

Issue #176: User Management

---

client/src/main/webjar/app.js
client/src/main/webjar/navigation-list/navigation-list.component.js
client/src/main/webjar/navigation-list/navigation-list.html
client/src/main/webjar/report-list/report-list.component.js
client/src/main/webjar/report-list/report-list.html
client/src/main/webjar/report-list/report-list.module.js
client/src/main/webjar/report-list/report-list.route.js
client/src/test/webjar/navigation-list/navigation-list.component.spec.js
client/src/test/webjar/report-list/report-list.component.spec.js

* Adds report-list state.
* Adds report-list to navigation list when logged in as admin.
Closes #247

Issue #247: CSV Report Export

---

client/src/main/webjar/create-user/create-user.component.js
client/src/main/webjar/create-user/create-user.html
client/src/main/webjar/create-user/create-user.module.js
client/src/main/webjar/create-user/create-user.scss
client/src/main/webjar/program-form-dialog/program-form-dialog.controller.js
client/src/main/webjar/user-form-dialog/user-form-dialog.controller.js
client/src/main/webjar/user-form-dialog/user-form-dialog.html
client/src/main/webjar/user-form-dialog/user-form-dialog.module.js
client/src/main/webjar/user-form-dialog/user-form-dialog.service.js
client/src/main/webjar/user-list/user-list.html
client/src/main/webjar/user-list/user-list.module.js
client/src/main/webjar/user-list/user-list.scss
client/src/test/webjar/create-user/create-user.component.spec.js
client/src/test/webjar/user-form-dialog/user-form-dialog.controller.spec.js
client/src/test/webjar/user-form-dialog/user-form-dialog.service.spec.js
src/main/java/org/hmhb/exception/user/UserEmailTooLongException.java
src/main/java/org/hmhb/organization/DefaultOrganizationService.java
src/main/java/org/hmhb/user/DefaultUserService.java
src/test/java/org/hmhb/user/DefaultUserServiceTest.java

* Adds create-user component to add new admins to the user list page.
* Adds more server side validation for a user's email.
* Updates the unit tests.

closes #295: Adds way to add admins before a login

---

build.gradle

* Updates gradle file to use explicit versions of dependencies.

closes #305: Use explicit versions

---

config/application.properties
src/main/java/org/hmhb/authentication/AuthenticationFilter.java
src/main/java/org/hmhb/authentication/DefaultAuthenticationService.java
src/main/resources/logback-spring.xml

* Removes unused hibernate properties (there were typos & not actually used).
* Changes configured log levels from DEBUG and TRACE to INFO.
* Fixes a few places that were inappropriately logging at info level.

closes #311: Turn off log noise

---

database/initial-data.sql

* Removes last team member's email from the initial admins now that the prod
environment is setup.

closes #316: Remove last team member email

---

integration-tests/input-customer-data.jmx

* Replaces non-ascii apostrophes with ascii ones.
* Adds explicit protocol so it's less typing when changing values for hitting
heroku.
* Updates a current jwt token for convenience.

closes #318: Update jmeter script

---

src/main/java/org/hmhb/authentication/AuthenticationController.java
src/test/java/org/hmhb/authentication/AuthenticationControllerTest.java

* Renames AuthenticationController create to authenticate.

closes #320: Clean up AuthController method name

---

README.md

* Adds postgres setup to README.md.
* Removes curls and TODOs from README.md.

closes #322: Update README

---

README.md
database/local-drop-everything.sql
database/local-setup.sql

* Adds more complete setup script for running PostgreSQL locally.
* Adds cleanup script for running PostgreSQL locally.
* Updates README.md with notes on how to setup and cleanup locally.

closes #325: Update README.md with DB setup info

---

client/README.md
client/src/main/webjar/authentication/authentication.config.js
src/main/java/org/hmhb/geocode/DefaultGoogleGeocodeClient.java
src/main/resources/templates/index.html

* Removes done TODOs.
* Clarifies authentication.config.js process.
Closes #327

Issue #327: Remove done TODOs.

---

database/local-setup.sql

* Fixes accidental granting of only SELECT by changing it to ALL PRIVILEGES.

closes #328: Fix Local DB Script

---

src/main/resources/templates/index.html

Signed-off-by: Ryan Bard <john.ryan.bard@gmail.com>

closes #332: Fix responsive issue on mobile
